### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by hakanceran64** [berkcangumusisik/YazilimcilarIcinKaynaklar#12]
Repoya bir LICENSE ekleyebilir miyiz?

**Comment by berkcangumusisik** [comment]
Onu nasıl ekleyebiliyoruz.

**Comment by berkcangumusisik** [comment]
Bilginiz varsa destek olursanız çok sevinirim.

**Comment by aysenurdeniz** [comment]
https://www.technopat.net/sosyal/konu/github-repositorye-lisans-atama.1229334/

Ayarlardan ekleme işlemini yapabilirsiniz.

**Comment by aysenurdeniz** [comment]
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository bu daha verimli bir sayfa olabilir.
